# List of plugins
set -g default-terminal "screen-256color"
set-option -g focus-events on
setw -g mode-keys vi
setw -g mouse on
set -g status-position top
set -g prefix ^A
set -g renumber-windows on

# Unbind default vi copy-mode bindings for hjkl
unbind -T copy-mode-vi h
unbind -T copy-mode-vi j
unbind -T copy-mode-vi k
unbind -T copy-mode-vi l

# Bind jkl; to navigate in copy mode
bind -T copy-mode-vi j send-keys -X cursor-left
bind -T copy-mode-vi k send-keys -X cursor-down
bind -T copy-mode-vi l send-keys -X cursor-up
bind -T copy-mode-vi ';' send-keys -X cursor-right

# Unbind the default Enter key in copy mode
unbind -T copy-mode-vi Enter

# Bind y to copy the selected text
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "git cpu-usage gpu-usage ram-usage"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)

# keep at the bottom
run '~/.config/tmux/plugins/tpm/tpm'
set-option -sa terminal-features ',XXX:RGB'
